# Text
BIG_TEXT = 40
TEXT = 30
SMALL_TEXT = 20
# Big button
BUTTON_BIG_HEIGHT = 4
BUTTON_BIG_WIDTH = 8
# Button
BUTTON_HEIGHT = 3
BUTTON_WIDTH = 6
# Small button
BUTTON_SMALL_HEIGHT = 2
BUTTON_SMALL_WIDTH = 10
